# Setup
name:         Conjunto compostela
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
